#include <avr/io.h>
#include "pins.h"

const Pin pins[] =
  {
    //0
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=0
    },
    //1
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=1
    },
    //2
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=2
    },
    //3
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=3
    },
    //4
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=4
    },
    //5
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=5
    },
    //6
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=6
    },
    //7
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=7
    },
    //8
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=0
    },
    //9
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=1
    },
    //10
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=2
    },
    //11
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=3
    },
    //12
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=4
    },
    //13
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=5
    }
  };
